@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 08 16:53:39 +0300 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_pwm_behav -key {Behavioral:sim_1:Functional:tb_pwm} -tclbatch tb_pwm.tcl -view C:/Users/Yusuf Soylu/Desktop/Vivado Projeleri/ders_11_PWM ile RGB Led/tb_pwm_behav.wcfg -log simulate.log"
call xsim  tb_pwm_behav -key {Behavioral:sim_1:Functional:tb_pwm} -tclbatch tb_pwm.tcl -view C:/Users/Yusuf Soylu/Desktop/Vivado Projeleri/ders_11_PWM ile RGB Led/tb_pwm_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
